### PR TITLE
update outlook setting

### PR DESCRIPTION
**Pull request by r10s**
- status is OK now as with
  https://github.com/deltachat/deltachat-core-rust/issues/1006
  we found a way to fix at least outlook.com+delta-to-delta communication

- server parameters updated, see
  https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-for-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040
  and login-settings (nice is that preparations are not needed btw!)

Screen Shot 2021-02-25 at 12 05 05

### CODE REVIEW

**Review by missytake — APPROVED** [review]
Nice!

**Review by missytake — CHANGES_REQUESTED** [review]
Something is broken, outlook appears in the preview only as an empty table row: https://testrun.org/provider/ab474df63b5acaa4f4af9463408840a54a5c141d/_site/

**Comment by missytake** [comment]
hm, it doesn't look fixed:

Screenshot_2021-02-28_01-29-09

**Comment by r10s** [comment]
hm, weird. the script for conversion to rust works, i just tried that.

**Comment by missytake** [comment]
Hm. Let's test in production, it should be finde.

**Comment by missytake** [comment]
It works now :) https://providers.delta.chat/outlook-com

**Comment by r10s** [comment]
> Let's test in production, it should be finde.

reminds me to "it compiles - let's ship it!" (slogan of a company i was working just after school ;)

**Pull request merged**
