### PR TITLE
Posteo domain alias update

### PR DESCRIPTION
**Pull request by gerryfrancis**
Update of Posteo alias domains (according to https://posteo.de/en/help/which-domains-are-available-to-use-as-a-posteo-alias-address)

### CODE REVIEW

**Review by r10s — CHANGES_REQUESTED** [review]
are really all `posteo.af` and `posteo.ru` accounts removed? i think, we cannot know that, the domains do work, so it is not improbable that also accounts exist with these domains. 

of course, might be, posteo does not offer new ones for $reasons

it is cheap for us to keep these domains, so, i would not remove them just by an "advertising" page.

**Comment by gerryfrancis** [comment]
> are really all posteo.af and posteo.ru accounts removed? i think, we cannot know that, the domains do work, so it is not improbable that also accounts exist with these domains.

@r10s Although the official list no longer includes domains for Afghanistan and Russia, I will try to get in contact with Posteo and ask them. Will post back here as soon as I have received a reply...

**Comment by r10s** [comment]
> Will post back here as soon as I have received a reply...

well, the answer may also strongly depend, you may get different answers from a technical or marketing views. if you get a qualified answer at all :)

doing a a quick search over "posteo.ru" i found at [least one address](https://www.expat.ru/resume.php), so they at least were in use at some point - also, the old list comes from somewhere.  if i would be a provider, i would let them run, even if you cannot register new ones.

also, i do not see any disadvantage in just letting posteo.ru and posteo.af in.

**Comment by gerryfrancis** [comment]
@r10s It might be possible that the requirements fulfilled by Posteo to operate in these two countries have changed, especially in Afghanistan. But let us wait for their response...

**Comment by r10s** [comment]
to move forward, let's just add the `posteo.ca` domain, which is unquestionable useful.

if we then get some feedback that says that posteo.ru are sold and are operated by some others now (i _really_ doubt that :), and needs different settings, we can handle that in a subsequent pr.

**Review by gerryfrancis — COMMENTED** [review]
Reinclude posteo.af and posteo.ru.

**Review by r10s — APPROVED** [review]

**Comment by r10s** [comment]
thanks a lot for taking care, @gerryfrancis

**Comment by gerryfrancis** [comment]
@r10s You are welcome! :)

**Pull request merged**
