### PR TITLE
added OVH and tiscali

### LINKED ISSUE #46: Add OVH Provider
# Basic information

**domain(s)**: ga-2.it 

**website of provider**: www.ovh.it

**works without preps**: NO 

### following preparations from the provider side: 

- [ ] setting a per-app password 
- [x] setting an option in provider's web interface 
- [ ] other: please describe 

### following advanced settings need to be set

neccessary manually typed advanced settings:

    smtp-server: ssl0.ovh.net
    smtp-port: 993
    smtp-security: SSL/TLS
    imap-server: ssl0.ovh.net
    imap-port: 465
    imap-security: SSL/TLS

### provider is funded by 
- [ ] advertisements 
- [x] recurring payments 
- [ ] donations 
- [ ] private/pro-bono for friends 

## other comments 

With OVH, there are problems receiving emails with Delta Chat.

### LINKED ISSUE #47: Add Tiscali Provider
## Basic information

**domain(s)**: tiscali.it

**website of provider**: www.tiscali.it

**works without preps**: YES

### following preparations from the provider side: 

- [ ] setting a per-app password 
- [ ] setting an option in provider's web interface 
- [ ] other: please describe 

### following advanced settings need to be set

neccessary manually typed advanced settings:

    smtp-server: *
    smtp-port: *
    smtp-security: *
    imap-server: *
    imap-port: *
    imap-security: *

### provider is funded by 
- [x] advertisements 
- [ ] recurring payments 
- [ ] donations 
- [ ] private/pro-bono for friends

### PR DESCRIPTION
**Pull request by missytake**
@andreaslattmann is this info correct? Do you just need your E-Mail password or do you need a special app password for Delta?

closes #46 

closes #47

### CODE REVIEW

**Comment by AndreasLattmann** [comment]
The OVH mail entry and exit server must be set manually on OVH, otherwise Delta Chat does not work.  Therefore the instructions given by OVH must be followed.  As for Tiscali, just enter your e-mail and password and it works without any problem.

**Comment by AndreasLattmann** [comment]
Sorry, I saw that I made a mistake on OVH.  The domain is not ga-2.it the OVH service requires domain registration.  Sorry for the mistake.

**Comment by missytake** [comment]
Ah, so they don't offer a default domain? It's fine, in theory we can add a list of domains they support, and if yours is one of them, why not.

When I looked on their website, I found this 0,99€/month, but if there are free plans, great :) I'll change it.

**Comment by missytake** [comment]
You know what? It doesn't make really much sense to change a lot in this area right now - we are still deciding on the data structure. I'll reopen #46, and add this later.

**Comment by Simon-Laux** [comment]
custom domain providers should be on the searchable list with imap/smtp config inside of the markdown part. We can't really detect them just yet (without dns queries in core) so I would say you can just look them up on the page (maybe even a custom filter like we have for working nicely).
Technically the domains just contain:
```
domains:
- custom
```
If we want we can even say that those providers aren't included in the crate except they have also own domains and are not exclusively providers where the user needs tho bring their own domain.

**Pull request merged**
