### PR TITLE
Style overhaul 2

### PR DESCRIPTION
**Pull request by missytake**
- [x] don't show auth column in the table on index.html
- [x] table only on the right half of the page
- [x] status column with nicer colors and shorter, white letters
- [ ] different ranking algorithm: popular and working providers to the top
- [ ] sort providers by name, status, or domains
- [x] drop date in the status column
- [x] better mobile view
- [x] explanation text for index.html
- [x] footer with disclaimer and link to delta.chat

### CODE REVIEW

**Comment by missytake** [comment]
Sorting the providers is not really doable with liquid, we would need to do it otherwise: https://stackoverflow.com/questions/8991995/using-liquid-to-sort-posts-alphabetically

**Comment by missytake** [comment]
Apart from the ranking, the layout is fixed so far. It's not perfect, but better than the status quo. @Simon-Laux merge?

**Comment by missytake** [comment]
okay, now I'm happy with it :) 

the new page doesn't look very nice yet, but it's not public yet anyway... :woman_shrugging:

**Comment by Simon-Laux** [comment]
> Sorting the providers is not really doable with liquid

we can use javascript for that, or we don't even stay with jekyll after we transformed our data structure it might make more sense to generate the site also with `build.rs`

**Pull request merged**
