### PR TITLE
added english before_login_hint for mail.ru

### LINKED ISSUE #168: Add a note that Mail.ru does not support IDLE and is not recommended
See https://github.com/deltachat/deltachat-core-rust/issues/1868

### PR DESCRIPTION
**Pull request by missytake**
@link2xt can you translate that sentence into russian? Otherwise we could also leave it in english...

closes #168

### CODE REVIEW

**Comment by link2xt** [comment]
"Не рекомендуется использовать mail.ru, потому что он разряжает вашу батарею быстрее, чем другие провайдеры."

But I would rather keep it in English since we don't have localization support.

**Comment by missytake** [comment]
Well, it's a russian provider, so I take it that most users would speak russian anyway? On the other hand, not many russians speak english, so for most cases it would be more useful to have it in russian, or not?

**Comment by missytake** [comment]
The provider's website is in russian - in https://github.com/deltachat/provider-db/pull/164#pullrequestreview-593070198 bjoern and I came to the conclusion that at least if the provider's website doesn't support english anyway, there is no good reason to keep the unlocalized hints in english.

**Review by link2xt — APPROVED** [review]
It actually supports english, once you click around it switches to english, but the front page always opens in russian for some reason.

**Comment by missytake** [comment]
Ah, so it's just very unfriendly to non-russian speaking users... because how would I know where to click^^ but well, not our job to fix their front page ;)

**Comment by link2xt** [comment]
> because how would I know where to click

You just click anywhere on the top row to switch to "mail" or "games" or whatever leads to the same domain.

**Pull request merged**
