### PR TITLE
Adding Migadu

### PR DESCRIPTION
**Pull request by cmahns**
Migadu is a hosted mail provider, and allows IMAP connectivity to any of its customer's domains.

### CODE REVIEW

**Comment by flub** [comment]
IIRC the only way to detect if a custom domain has email hosted by migadu is to look at the MX record:

```
$ dig -t MX custom.example.com
...
;; ANSWER SECTION:
custom.example.com.		3000	IN	MX	20 aspmx2.migadu.com.
custom.example.com.		3000	IN	MX	10 aspmx1.migadu.com.
```

Does this configuration make deltachat detect this?  That would be cool as this has annoyed me in the past.  I'm not very familiar with how the provider db works though.

**Comment by flub** [comment]
> MX records are currently used only for Gmail for security reasons: https://github.com/deltachat/deltachat-core-rust/blob/3efbe5b1ef5a7afe9ba66fc41042d9afe22883a8/src/provider.rs#L215-L249 We may add Migadu as an exception as well if needed, but overall trusting MX records retrieved over insecure DNS does not scale as it is too easy to redirect the client during configuration to one compromised provider and the client will send the password there.

So what is the implication of an exception?  Trusting that it's "always" safe to send a password to migadu.com servers and that they won't try and steal it if it isn't for them?

I know the XML autoconfig is the best option, but it requires an http server and this is not handled my migadu, while they do help you setup the other aspects (my migadu domain doesn't even have an http server).

**Comment by r10s** [comment]
> Yes, because your ISP can hijack MX record request and say that any provider not in the provider database is handled by migadu, then you will try to connect to migadu and send them the password.

to get it right, to get the password finally, your ISP needs to work together with Migadu then?

**Comment by flub** [comment]
Basically the question here is whether we'd worry for migadu to ever become a malicious actor.  My guess is that this would only be the case if they are legally compelled, but what do I know.

More generally I'm not sure why gmail did get this exception.  My slightly more liberal exception would be to allow any "reputable" email provider to be on the exception list.  That still stops a MITM attack with a custom server setup just for the purpose of the MITM.  But I see little value in disallowing using MX records entirely.

**Pull request closed without merging**
