### PR TITLE
add yggmail

### PR DESCRIPTION
**Pull request by r10s**
that should make configuration a bit easier :)

however, it should still be possible to use different ports.

### CODE REVIEW

**Comment by missytake** [comment]
Is the yggmail companion app publicly available somewhere? We should add a link + some text on why you need it on the provider page.

**Comment by r10s** [comment]
> Is the yggmail companion app publicly available somewhere? We should add a link + some text on why you need it on the provider page.

not as far as i know, if you know more details, feel free to add them :)

**Comment by missytake** [comment]
btw, did anyone try to get yggmail running with deltachat-desktop?

**Review by missytake — APPROVED** [review]

**Comment by r10s** [comment]
> btw, did anyone try to get yggmail running with deltachat-desktop?

@adbenitez ?

**Pull request merged**
