### PR TITLE
add buzon.uy

### PR DESCRIPTION
**Pull request by r10s**
cc @adbenitez

### CODE REVIEW

**Comment by link2xt** [comment]
Makes sense to also add https://undernet.uy/ while we are at it.

**Comment by r10s** [comment]
> Makes sense to also add https://undernet.uy/ while we are at it.

is it just another domain in buzon.uy.md or is it completely independent? i do not know that service and did not find information at the first glance.

**Comment by link2xt** [comment]
It is a different server running on a different IP, but they link to each other on the front page and undernet.by has ports 587 and 143 open, with working SMTP and IMAP starttls TLSv1.3 setups.

The difference is that undernet.by does not have 993. I don't know much about these servers too, but makes sense to add undernet.by with strict TLS for 143 and 587.

**Comment by r10s** [comment]
@link2xt added undernet.by as suggested, not sure about strict_tls for buzon.uy - where did you find the strict-tls-info for undernet.by?

**Comment by link2xt** [comment]
> where did you find the strict-tls-info for undernet.by?

You can connect with `openssl s_client -connect undernet.uy:143 -starttls imap -crlf` and `openssl s_client -connect undernet.uy:587 -starttls smtp -crlf`, there are Let's Encrypt TLS certificates.

**Comment by r10s** [comment]
merging in, was just discussed on irc

**Pull request merged**
