### PR TITLE
Update icloud.md for Custom Email Domain

### PR DESCRIPTION
**Pull request by Amzd**
Figured out how to use Custom Email Domain hosted on iCloud+. I'd like to update the description of iCloud provider to maybe save the next person some time.

I don't know if formatting lists the way I did works in provider description (or if this is even the right place to add this information) so please let me know if this is wrong.

### CODE REVIEW

**Review by r10s — APPROVED** [review]

**Comment by r10s** [comment]
thanks a lot!❤️

and formatting looks good to me 👌

**Comment by Amzd** [comment]
@r10s your approval was not enough to merge, should I assign someone?

**Comment by r10s** [comment]
it got merged, thanks @missytake 

btw: this is how it looks like rendered: https://providers.delta.chat/icloud - the page will be accessible directly from within the app whenever one of the icloud domain is typed in

**Comment by Amzd** [comment]
Cool, thanks! I noticed now on the website I should have updated the `Last checked` but that's not a big deal I think.

**Comment by r10s** [comment]
i changed the date, thanks again!

**Pull request merged**
