### PR TITLE
added purelyemail.com

### LINKED ISSUE #269: Add provider Purelymail.com
I have been using Purelymail.com with great success.

**Domain(s):**
- purelymail.com
- cheapermail.com
- placeq.com
- rethinkmail.com
- worldofmail.com

**Website of provider:** purelymail.com

**Does it work without Preparations?**  Yes

**Do you know which servers the provider uses?**

imap-server: imap.purelymail.com
imap-port: 993
imap-security-socket: SSL/TLS

smtp-server: smtp.purelymail.com
smtp-port: 465
smtp-security-socket: SSL/TLS

### PR DESCRIPTION
**Pull request by missytake**
fixes #269

### CODE REVIEW

**Review by r10s — DISMISSED** [review]

**Comment by r10s** [comment]
did not test, however, maybe we should: smtp.purelyemail.com seems not to work

**Comment by missytake** [comment]
> did not test, however, maybe we should: smtp.purelyemail.com seems not to work

that was my typo^^

**Review by r10s — APPROVED** [review]
did not test, but if ci passes, things should be fine :)

**Comment by sysfu** [comment]
There's a typo in the web site name. It should be purelymail.com vs. purely**e**mail.com

**Comment by r10s** [comment]
thanks a lot for looking closely, @sysfu 🙏

it hotfixed that on master, should be fine now: https://github.com/deltachat/provider-db/blob/master/_providers/purelymail.com.md

(nb: it seems to be a hard to spell address, i personally would go for the also offered rethinkmail-domain then :)

**Pull request merged**
