### PR TITLE
Add systemli.org as delta chat provider

### PR DESCRIPTION
**Pull request by xshadow**

### CODE REVIEW

**Comment by missytake** [comment]
Thanks a lot!

**Comment by r10s** [comment]
has someone tested that? 

i think, systemli would stop working after this.

the server, systemli requires is mail.systemli.org - Delta Chat knows about this server because of  https://www.systemli.org/.well-known/autoconfig/mail/config-v1.1.xml - but if we define a provider-db-entry, this step is skipped, so only some defaults are probed - and mail.systemli.org seems not to be among them

so, we should either revert this commit - or add the correct server entries.

**Comment by r10s** [comment]
but it would make sense to add the server section - that way, startup would be faster and more reliable.

**Comment by xshadow** [comment]
Hey @r10s, we verified that systemli.org is working correct with delta-chat. 

My assumption was that delta chat would check the autoconfigugration  in [https://www.systemli.org/.well-known/autoconfig/mail/config-v1.1.xml](https://www.systemli.org/.well-known/autoconfig/mail/config-v1.1.xml). That would have the benefit, that we as systemli.org could change our autoconfiguration settings, whenever we want/have to. So we won't have a second place, where we store our mailsetup configuration publically. Because second places get easily forgotten and in the end it won't work. 

Please correct me if this assumption was wrong!

**Comment by r10s** [comment]
we do check https://www.systemli.org/.well-known/autoconfig/mail/config-v1.1.xml - but we do not if there is a provider-db entry with _more than just OK_, i've just filed an issue for that at #113 - this is not systemli-specific, however, i've used it as an example there.

**Comment by xshadow** [comment]
Okay. But would there be a better place, if you do not want to store the information twice?

**Pull request merged**
