### PR TITLE
added e.email

### LINKED ISSUE #161: Add E.Foundation
Domain: e.email
It works perfectly fine
Sign Up: https://e.foundation/e-email-invite/
Login: https://ecloud.global/login
IMAP/SMTP-Server: mail.ecloud.global (https://e.foundation/email-configuration/)

Provider is funded by:
- Donations
- Subscriptions for more space

### PR DESCRIPTION
**Pull request by missytake**
closes #161

### CODE REVIEW

**Comment by missytake** [comment]
I didn't test it myself, but @mawoka-myblock did?

**Review by r10s — APPROVED** [review]
compared against https://e.foundation/email-configuration/, lgtm, did not test, however.

**Comment by mawoka-myblock** [comment]
I tested it

**Comment by missytake** [comment]
Thanks!

**Pull request merged**
